### PR TITLE
Added 'getQuote' method, with example

### PR DESCRIPTION
**Pull request by dmojdehi**
Uses Homeaway's api to get a quote for a listing (& unitId).  Caller must provide checkin, checkout, and number of adults staying.

### CODE REVIEW

**Comment by alexarena** [comment]
Thanks for the contribution! A few quick qs:

1. Any reason why the example listing was changed? 
2. How do you feel about having arrival and departure dates be `Date` objects vs. strings. I'm imagining this would be more neutral vs. mandating a specific format. Open to arguments against it, though.

**Comment by dmojdehi** [comment]
> Any reason why the example listing was changed?

The listing id wasn't working for me, (returned as invalid?) so I assume it had been de-listed and entered a new one.  

> How do you feel about having arrival and departure dates be Date objects vs. strings

It exposes what their API accepts; strings in yyyy-mm-dd format.  For a thin api wrapper that seemed best.  Date objects introduce questions about timezones (is it the date in UTC? the listing's local timezone? the callers timezones? or your server?), and may not even be convenient for everyone. (it wouldn't be for me, fwiw).

**Comment by alexarena** [comment]
All good points on date, let's leave it as you wrote it.

I'm getting 400'd (There was no unit...) when trying to get a quote on `6592159`. Weirdly, though, getting the listing works just fine. I think there's a note in the HA dev docs about this. Seems like a problem on their end. Might add their note to the 400 error we're getting in a future PR.

Either way, nothing to stop me from merging this now. Thanks for your contribution!

**Comment by alexarena** [comment]
^ added that issue for docs on this one. I'll add once I get a chance but would be happy to review a PR.

**Comment by dmojdehi** [comment]
No problem, thanks for making this module!  


Re 400- no unit
Yes the unit is required to get a quote. But the listing didn’t have one?? Strange.

**Pull request merged**
